interval = 5
platform = "alpaca"

[[tactics]]
name = "VTI"

[tactics.buy]
for = { stock = "VTI" }
when = { below_median_percent = 1.0 }
do = { buy_percent = 24 }

[tactics.sell]
for = { stock = "VTI" }
when = { gain_above_percent = 1.2 }
do = { sell_all = true }

[[tactics]]
name = "SH"

[tactics.buy]
for = { stock = "SH" }
when = { below_median_percent = 1.0 }
do = { buy_percent = 6 }

[tactics.sell]
for = { stock = "SH" }
when = { gain_above_percent = 1.0 }
do = { sell_all = true }

[[tactics]]
name = "VEA"

[tactics.buy]
for = { stock = "VEA" }
when = { below_median_percent = 0.9 }
do = { buy_percent = 20 }

[tactics.sell]
for = { stock = "VEA" }
when = { gain_above_percent = 0.9 }
do = { sell_all = true }

[[tactics]]
name = "VWO"

[tactics.buy]
for = { stock = "VWO" }
when = { below_median_percent = 1.1 }
do = { buy_percent = 15 }

[tactics.sell]
for = { stock = "VWO" }
when = { gain_above_percent = 1.25 }
do = { sell_all = true }

[[tactics]]
name = "VIG"

[tactics.buy]
for = { stock = "VIG" }
when = { below_median_percent = 1.8 }
do = { buy_percent = 8 }

[tactics.sell]
for = { stock = "VIG" }
when = { gain_above_percent = 1.25 }
do = { sell_all = true }

[[tactics]]
name = "XLE"

[tactics.buy]
for = { stock = "XLE" }
when = { below_median_percent = 1.2 }
do = { buy_percent = 5 }

[tactics.sell]
for = { stock = "XLE" }
when = { gain_above_percent = 0.55 }
do = { sell_all = true }

[[tactics]]
name = "VTEB"

[tactics.buy]
for = { stock = "VTEB" }
when = { below_median_percent = 0.5 }
do = { buy_percent = 15 }

[tactics.sell]
for = { stock = "VTEB" }
when = { gain_above_percent = 0.3 }
do = { sell_all = true }

[[tactics]]
name = "VXX"

[tactics.buy]
for = { stock = "VXX" }
when = { below_median_percent = 4.9 }
do = { buy_percent = 7.0 }

[tactics.sell]
for = { stock = "VXX" }
when = { gain_above_percent = 3.4 }
do = { sell_all = true }