interval = 2
platform = "alpaca"

[[tactics]]
name = "Sell off"

[tactics.sell]
for = { all_other_positions = true }
when = { gain_above_percent = 1.0 }
do = { sell_all = true }

[[strategies]]
name = "ETFs"
path = "etf-hold.csv"
portfolio_percent = 70.0

[[strategies]]
name = "Chaos"
path = "chaos.csv"
portfolio_percent = 30.0

